language: bash

sudo: required

os:
    - linux

script:
    - ./buildSplice.sh

      #language: python
      #python:
      #  - "3.6"      # current default Python on Travis CI
      ## command to run tests
      #script: python buildSplice.py
