language: bash

sudo: required

os:
    - linux

services:
  - docker

script:
    - echo `pwd`
    - ls -l
    - ls -la $HOME
    - cd base
    - chmod 777 build.sh
    - ./build.sh


      #deploy:
      #  provider: script
      #  script: bash docker_push
      #  on:
      #    branch: master

addons:
  apt:
    packages:
    - maven

cache:
    directories:
     - /home/travis/.m2/
     - $HOME/.m2

      #language: python
      #python:
      #  - "3.6"      # current default Python on Travis CI
      ## command to run tests
      #script: python buildSplice.py

