language: bash

sudo: required

os:
    - linux

script:
    - echo `pwd`
    - ls -l
    - ls -la $HOME
    - chmod 777 buildSplice.sh
    - ./buildSplice.sh

addons:
  apt:
    packages:
    - maven

cache:
    directories:
     - /home/travis/.m2/
     - $HOME/.m2

      #language: python
      #python:
      #  - "3.6"      # current default Python on Travis CI
      ## command to run tests
      #script: python buildSplice.py
