version: 2
jobs:
  build:
    working_directory: ~/longdb
    docker:
      #- image: circleci/openjdk:8-jdk-stretch
      #- image: circleci/openjdk:8u242-buster-node-browsers-legacy
      #- image: circleci/openjdk:11-jdk-buster-node-browsers-legacy
      #- image: circleci/openjdk:11-jdk-buster-node-browsers
      #- image: circleci/openjdk:13-browsers-legacy
      #- image: circleci/openjdk:  8u242-jdk-buster-node-browsers-legacy
      #- image: circleci/openjdk:8-jdk-stretch-node-browsers
    - image: circleci/node:10

    steps:
    - checkout

    - run: env

    #- run: mvn -X -e -f view/pom.xml compile -DskipTests 
    - run: 
        working_directory: ~/longdb/view
        command: |
           npm cache clean --force
           npm install
      
    - run: 
        working_directory: ~/longdb/view
        command: npm run build


    - restore_cache:
        key: longdb-admin-{{ checksum "server/pom.xml" }}

    - run: mvn -f server/pom2.xml dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: longdb-csd-{{ checksum "server/pom.xml" }}
    - run: mvn -f server/pom2.xml package -DskipTests
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: /home/circleci/.npm/_logs
        
workflows:
  version: 2
  workflow:
    jobs:
    - build
